#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# RICE(0) guarda su configuración local en .env.local: es lo que lee `next
# dev` y lo que .gitignore mantiene fuera del repo.
ENV_FILE=".env.local"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# project_ref extrae la referencia del proyecto de la URL de Supabase
# (https://<ref>.supabase.co), que es lo que arma todas las URLs del panel.
project_ref() {
  local url; url=$(_existing NEXT_PUBLIC_SUPABASE_URL || true)
  url="${url#https://}"
  printf '%s' "${url%%.supabase.co*}"
}

banner "RICE(0) — provisionar Supabase"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Supabase: crear el proyecto"
say "RICE(0) guarda Proyectos, Versiones y Nodos en Postgres, con la sesión"
say "en Supabase Auth. Empezamos por crear el proyecto que los alojará."
open_url "https://supabase.com/dashboard/projects"
step "Pulsa 'New project' y elige tu organización."
step "Nombre: rice-zero (o el que prefieras)."
step "Guarda la contraseña de la base de datos en tu gestor: solo se enseña una vez."
step "Región: la más cercana a tus usuarios."
step "Plan Free."
warn "Aprovisionar tarda un par de minutos. Espera al estado 'Active' antes de seguir."
pause "¿El proyecto está activo?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Supabase: URL y clave publicable"
say "Estas dos credenciales van al navegador. Son públicas por diseño: toda"
say "la autorización vive en las políticas RLS que aplicaremos en la etapa 3."
open_url "https://supabase.com/dashboard/project/_/settings/api-keys"
step "Elige tu proyecto si el panel te lo pide."
step "Copia 'Project URL' (https://<ref>.supabase.co)."
ask NEXT_PUBLIC_SUPABASE_URL "Pega la Project URL:"
step "En 'Publishable key', copia la clave que empieza por sb_publishable_."
warn "La clave 'secret' (sb_secret_) NO la queremos: RICE(0) nunca la usa."
ask NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "Pega la clave publicable:"
write_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"

REF="$(project_ref)"
if [[ -z "$REF" ]]; then
  warn "no pude deducir la referencia del proyecto de esa URL"
  ask REF "Escribe la referencia del proyecto (el <ref> de <ref>.supabase.co):"
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Supabase: aplicar el esquema"
say "El esquema es UNO, compartido por todos los Proveedores de Backend"
say "(db/migrations/), más un preludio corto por proveedor (db/preludes/) que"
say "aporta la identidad del usuario, la FK a su tabla de cuentas y el nombre"
say "del rol anónimo."
note "Crea las cuatro tablas, activa RLS owner-only y define la RPC que clona"
note "una Versión con su árbol entero. Va en una sola transacción: si algo"
note "falla, no queda un esquema a medias."
say ""
say "Para aplicarlo hace falta una conexión directa a Postgres."
open_url "https://supabase.com/dashboard/project/$REF/settings/database"
step "En 'Connection string' → 'URI', copia la cadena y sustituye [YOUR-PASSWORD]"
step "por la contraseña de la base de datos de la etapa 1."
warn "Es del rol postgres, que se salta TODAS las políticas. Sirve para aplicar"
warn "migraciones y para nada más. Nunca en código de aplicación ni en una"
warn "variable NEXT_PUBLIC_."
ask_secret SUPABASE_DB_URL "Pega la connection string:"
write_env SUPABASE_DB_URL "$SUPABASE_DB_URL"

if SUPABASE_DB_URL="$SUPABASE_DB_URL" node scripts/apply-schema.mjs supabase; then
  say "Esquema aplicado."
else
  SKIPPED+=("aplicar el esquema: node scripts/apply-schema.mjs supabase")
  warn "la migración falló; revisa el mensaje de arriba antes de seguir"
fi
pause "Enter para seguir"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Supabase: verificar aislamiento y clonado"
say "Ahora comprobamos las dos garantías que sostienen el producto, contra el"
say "motor real: que un segundo usuario no llega a tus datos, y que clonar una"
say "Versión copia el árbol completo con la jerarquía remapeada."
note "Crea dos usuarios de prueba y hace rollback: no deja rastro."
if SUPABASE_DB_URL="$SUPABASE_DB_URL" node scripts/verify-schema.mjs supabase --applied; then
  say "Aislamiento y clonado verificados."
else
  SKIPPED+=("verificar el esquema: node scripts/verify-schema.mjs supabase --applied")
  warn "seguimos con la configuración, pero revisa esto antes de escribir código"
fi
pause "Enter para seguir"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: cliente OAuth"
say "Para 'Entrar con Google' necesitamos un cliente OAuth de Google que"
say "confíe en el endpoint de callback de tu proyecto Supabase."
note "URL de callback: https://$REF.supabase.co/auth/v1/callback"
open_url "https://console.cloud.google.com/apis/credentials"
step "Crea (o elige) un proyecto en Google Cloud."
step "Si te lo pide, configura primero la pantalla de consentimiento OAuth: tipo 'External', con nombre de app y correo de soporte."
step "Credentials → Create credentials → OAuth client ID → Application type: Web application."
step "En 'Authorized redirect URIs' añade exactamente: https://$REF.supabase.co/auth/v1/callback"
step "Crea el cliente. Google enseña el Client ID y el Client secret."
warn "Deja esa pestaña abierta: los pegas en Supabase en la etapa siguiente."
note "Las guarda Supabase, no .env.local: RICE(0) nunca lee esas credenciales, así que el wizard tampoco las toca."
pause "¿Cliente OAuth creado y credenciales a la vista?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Supabase: proveedores y URLs de sesión"
say "Le damos a Supabase el cliente de Google y le decimos a dónde devolver al"
say "usuario tras autenticarse."
open_url "https://supabase.com/dashboard/project/$REF/auth/providers"
step "Abre 'Email': deja 'Confirm email' ACTIVADO (registrarse exige confirmar por correo)."
step "Abre 'Google': actívalo."
step "Pega el Client ID y el Client secret de la pestaña de Google."
step "Guarda."
pause "¿Google guardado y Email con confirmación activa?"
open_url "https://supabase.com/dashboard/project/$REF/auth/url-configuration"
step "Site URL: http://localhost:3000 mientras desarrollas."
step "En 'Redirect URLs' añade http://localhost:3000/**"
step "Cuando tengas el dominio de Vercel (etapa 7), vuelve aquí y añade https://<tu-dominio>/** como Redirect URL."
step "Guarda."
pause "¿URLs guardadas?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Vercel: proyecto y variables de entorno"
say "Último paso: el proyecto en Vercel con las mismas dos credenciales, para"
say "que el despliegue hable con el mismo Supabase que tu entorno local."

# push_vercel_env NAME VALUE ENTORNO reemplaza la variable en ese entorno.
# `vercel env add` no sobrescribe, así que se borra antes: hace el wizard
# repetible sin dejar duplicados ni valores viejos.
push_vercel_env() {
  local name="$1" value="$2" entorno="$3"
  npx --yes vercel@latest env rm "$name" "$entorno" --yes >/dev/null 2>&1 || true
  if printf '%s' "$value" | npx --yes vercel@latest env add "$name" "$entorno" >/dev/null 2>&1; then
    printf '  %s✓ %s%s en %s\n' "$GREEN" "$name" "$RESET" "$entorno"
  else
    SKIPPED+=("variable $name en Vercel ($entorno)")
    warn "no pude escribir $name en $entorno"
  fi
}

if confirm "¿Uso la CLI de Vercel (npx vercel) para hacerlo por ti?"; then
  say "Se abrirá el login de Vercel si aún no has entrado."
  if npx --yes vercel@latest link; then
    for entorno in production preview development; do
      push_vercel_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL" "$entorno"
      push_vercel_env NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY" "$entorno"
    done
    say "Despliega cuando quieras con: npx vercel --prod"
    step "Cuando Vercel te dé el dominio, vuelve a las URLs de Supabase y añade https://<tu-dominio>/** como Redirect URL."
    pause "Entendido"
  else
    SKIPPED+=("enlazar el proyecto con Vercel (npx vercel link)")
    warn "el enlace con Vercel falló; hazlo desde el panel"
  fi
else
  open_url "https://vercel.com/new"
  step "Importa el repositorio mickel-arroz/rice-zero."
  step "En 'Environment Variables' añade, para Production, Preview y Development:"
  step "  NEXT_PUBLIC_SUPABASE_URL = $NEXT_PUBLIC_SUPABASE_URL"
  step "  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = (la clave publicable de la etapa 2)"
  step "Despliega."
  pause "¿Proyecto creado con sus variables?"
  step "Vuelve a la configuración de URLs de Supabase y añade https://<tu-dominio>/** como Redirect URL."
  pause "¿Añadida?"
fi

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Activar el interruptor"
say "Una variable decide qué Proveedor de Backend está activo. Sin esta línea,"
say "la app sigue hablando con el otro proveedor por bien configurado que esté"
say "éste."
write_env NEXT_PUBLIC_BACKEND "supabase"
note "En Vercel hay que ponerla también, o el despliegue seguirá apuntando a"
note "Neon."
SKIPPED+=("NEXT_PUBLIC_BACKEND=supabase en Vercel (los tres entornos)")

finish
