#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE=".env.local"

PROJECT_URL="https://console.neon.tech/app/projects/shy-river-68096283"
BRANCH="branches/br-nameless-flower-aylt165n"

banner "RICE(0) — provisionar Neon"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Auth: verificación de email obligatoria"
say "El proyecto, el Data API y Neon Auth ya están creados. Sign-up y"
say "sign-in con email están activos y Google OAuth ya usa shared keys."
say "Falta un toggle."
open_url "$PROJECT_URL/$BRANCH/auth?tab=configuration"
step "En la sección Authentication, activa 'Verify at Sign-up'."
note "Sin él, un usuario entra sin verificar el correo. El spec lo exige."
note "Los correos los manda Neon: email provider Shared, remitente"
note "auth@mail.myneon.app. No hace falta Resend ni SMTP."
say ""
warn "Aviso del propio Neon: cualquiera en internet puede registrarse en tu"
warn "app ('restricted signups coming soon'). La RLS aísla a cada usuario,"
warn "así que no hay fuga de datos, pero el registro está abierto."
pause "Cuando el toggle esté en verde, Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Connection string (solo migraciones)"
open_url "$PROJECT_URL/$BRANCH/credentials"
step "Copia la connection string de la branch production."
warn "Es del rol neondb_owner, que tiene BYPASSRLS: se salta TODAS las"
warn "políticas. Sirve para aplicar migraciones y para nada más. Nunca en"
warn "código de aplicación ni en una variable NEXT_PUBLIC_."
ask_secret DATABASE_URL "Pega la connection string:"
write_env DATABASE_URL "$DATABASE_URL"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Data API"
say "Es el endpoint PostgREST contra el que habla el navegador. Ya está"
say "habilitado; solo hay que copiar la URL."
open_url "$PROJECT_URL/$BRANCH/data-api"
step "Copia la API URL."
note "Tiene la forma https://ep-....apirest.<region>.aws.neon.tech/neondb/rest/"
ask NEXT_PUBLIC_NEON_DATA_API_URL "Pega la API URL:"
write_env NEXT_PUBLIC_NEON_DATA_API_URL "$NEXT_PUBLIC_NEON_DATA_API_URL"
say ""
warn "Si alguna vez ves la casilla 'Grant public schema access', NO la marques."
note "Ejecuta GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES ... TO"
note "authenticated, y contradice la migración: ai_analyses solo debe tener"
note "select/insert/delete. Un Análisis se crea, se lee y se borra, pero no"
note "se edita. El bloque de revoke de la migración lo corrige, pero mejor"
note "no repartir permisos de más."
note "Los roles del Data API son 'authenticated' y 'anonymous'. La migración"
note "dice 'anon' (nombre de Supabase): ese renombrado va en el preludio."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Auth URL y JWKS"
say "El JWKS público es lo que permite que el navegador hable DIRECTO con el"
say "Data API: Neon Auth firma el JWT, pg_session_jwt verifica la firma"
say "contra estas claves, y auth.uid() devuelve el uuid del usuario."
note "Es el modo 'con JWK configurado', no el de compatibilidad PostgREST"
note "que confía en claims puestos por la aplicación."
open_url "$PROJECT_URL/$BRANCH/auth?tab=configuration"
step "En Project Info, copia la Auth URL."
ask NEXT_PUBLIC_NEON_AUTH_URL "Pega la Auth URL:"
write_env NEXT_PUBLIC_NEON_AUTH_URL "$NEXT_PUBLIC_NEON_AUTH_URL"
step "Copia la JWKS URL."
ask NEON_JWKS_URL "Pega la JWKS URL:"
write_env NEON_JWKS_URL "$NEON_JWKS_URL"
say ""
note "Better Auth para Next.js documenta además NEON_AUTH_COOKIE_SECRET, que"
note "la consola no publica. Sale del 'Open quickstart' de la página de Auth."
SKIPPED+=("NEON_AUTH_COOKIE_SECRET: sacarlo del quickstart de Neon Auth")

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Aplicar el esquema"
say "El esquema es UNO, compartido por todos los Proveedores de Backend"
say "(db/migrations/), más un preludio corto por proveedor (db/preludes/)."
note "El preludio de Neon aporta app.current_user_id() sobre auth.uid() de"
note "pg_session_jwt, la FK a neon_auth.\"user\" y el nombre del rol anónimo."
warn "app.current_user_id() es 'security definer' y no es decorativo: el rol"
warn "'authenticated' NO tiene USAGE sobre el esquema auth en Neon, así que una"
warn "política que llame a auth.uid() en línea falla con 42501."
say ""
say "Va en una sola transacción: si algo falla, no queda un esquema a medias."
if node scripts/apply-schema.mjs neon; then
  say "Esquema aplicado."
else
  SKIPPED+=("aplicar el esquema: node scripts/apply-schema.mjs neon")
  warn "la migración falló; revisa el mensaje de arriba antes de seguir"
fi
pause "Enter para seguir"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Verificar aislamiento y clonado"
say "Las dos garantías que sostienen el producto, contra el motor real: que un"
say "segundo usuario no llega a tus datos, y que clonar una Versión copia el"
say "árbol completo con la jerarquía remapeada."
note "Crea dos usuarios de prueba y hace rollback: no deja rastro."
if node scripts/verify-schema.mjs neon --applied; then
  say "Aislamiento y clonado verificados."
else
  SKIPPED+=("verificar el esquema: node scripts/verify-schema.mjs neon --applied")
  warn "seguimos, pero revisa esto antes de escribir código"
fi
pause "Enter para seguir"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Activar el interruptor"
say "Una variable decide qué Proveedor de Backend está activo. Cambiarla y"
say "redesplegar es todo lo que hace falta para volver a Supabase."
write_env NEXT_PUBLIC_BACKEND "neon"
say ""
note "En Vercel hay que ponerla también, o el despliegue seguirá apuntando al"
note "otro proveedor."
SKIPPED+=("NEXT_PUBLIC_BACKEND=neon en Vercel (los tres entornos)")

finish
