#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# La biblioteca (UX, prompts, escritura de .env) vive en `scripts/wizard-lib.sh`
# y la comparten todos los wizards. Aquí abajo van solo las etapas de ESTE
# proveedor.

set -euo pipefail

# shellcheck source=scripts/wizard-lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/wizard-lib.sh"

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE=".env.local"

PROJECT_URL="https://console.neon.tech/app/projects/shy-river-68096283"
BRANCH="branches/br-nameless-flower-aylt165n"

banner "RICE(0) — provisionar Neon"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Auth: verificación de email obligatoria"
say "El proyecto, el Data API y Neon Auth ya están creados. Sign-up y"
say "sign-in con email están activos y Google OAuth ya usa shared keys."
say "Falta un toggle."
open_url "$PROJECT_URL/$BRANCH/auth?tab=configuration"
step "En la sección Authentication, activa 'Verify at Sign-up'."
note "Sin él, un usuario entra sin verificar el correo. El spec lo exige."
note "Los correos los manda Neon: email provider Shared, remitente"
note "auth@mail.myneon.app. No hace falta Resend ni SMTP."
say ""
warn "Aviso del propio Neon: cualquiera en internet puede registrarse en tu"
warn "app ('restricted signups coming soon'). La RLS aísla a cada usuario,"
warn "así que no hay fuga de datos, pero el registro está abierto."
pause "Cuando el toggle esté en verde, Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Connection string (solo migraciones)"
open_url "$PROJECT_URL/$BRANCH/credentials"
step "Copia la connection string de la branch production."
warn "Es del rol neondb_owner, que tiene BYPASSRLS: se salta TODAS las"
warn "políticas. Sirve para aplicar migraciones y para nada más. Nunca en"
warn "código de aplicación ni en una variable NEXT_PUBLIC_."
ask_secret DATABASE_URL "Pega la connection string:"
write_env DATABASE_URL "$DATABASE_URL"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Data API"
say "Es el endpoint PostgREST contra el que habla el navegador. Ya está"
say "habilitado; solo hay que copiar la URL."
open_url "$PROJECT_URL/$BRANCH/data-api"
step "Copia la API URL."
note "Tiene la forma https://ep-....apirest.<region>.aws.neon.tech/neondb/rest/"
ask NEXT_PUBLIC_NEON_DATA_API_URL "Pega la API URL:"
write_env NEXT_PUBLIC_NEON_DATA_API_URL "$NEXT_PUBLIC_NEON_DATA_API_URL"
say ""
warn "Si alguna vez ves la casilla 'Grant public schema access', NO la marques."
note "Ejecuta GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES ... TO"
note "authenticated, y contradice la migración: ai_analyses solo debe tener"
note "select/insert/delete. Un Análisis se crea, se lee y se borra, pero no"
note "se edita. El bloque de revoke de la migración lo corrige, pero mejor"
note "no repartir permisos de más."
note "Los roles del Data API son 'authenticated' y 'anonymous'. La migración"
note "dice 'anon' (nombre de Supabase): ese renombrado va en el preludio."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Auth URL y JWKS"
say "El JWKS público es lo que permite que el navegador hable DIRECTO con el"
say "Data API: Neon Auth firma el JWT, pg_session_jwt verifica la firma"
say "contra estas claves, y auth.uid() devuelve el uuid del usuario."
note "Es el modo 'con JWK configurado', no el de compatibilidad PostgREST"
note "que confía en claims puestos por la aplicación."
open_url "$PROJECT_URL/$BRANCH/auth?tab=configuration"
step "En Project Info, copia la Auth URL."
ask NEXT_PUBLIC_NEON_AUTH_URL "Pega la Auth URL:"
write_env NEXT_PUBLIC_NEON_AUTH_URL "$NEXT_PUBLIC_NEON_AUTH_URL"
step "Copia la JWKS URL."
ask NEON_JWKS_URL "Pega la JWKS URL:"
write_env NEON_JWKS_URL "$NEON_JWKS_URL"
say ""
note "Better Auth para Next.js documenta además NEON_AUTH_COOKIE_SECRET, que"
note "la consola no publica. Sale del 'Open quickstart' de la página de Auth."
SKIPPED+=("NEON_AUTH_COOKIE_SECRET: sacarlo del quickstart de Neon Auth")

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Aplicar el esquema"
say "El esquema es UNO, compartido por todos los Proveedores de Backend"
say "(db/migrations/), más un preludio corto por proveedor (db/preludes/)."
note "El preludio de Neon aporta app.current_user_id() sobre auth.uid() de"
note "pg_session_jwt, la FK a neon_auth.\"user\" y el nombre del rol anónimo."
warn "app.current_user_id() es 'security definer' y no es decorativo: el rol"
warn "'authenticated' NO tiene USAGE sobre el esquema auth en Neon, así que una"
warn "política que llame a auth.uid() en línea falla con 42501."
say ""
say "Va en una sola transacción: si algo falla, no queda un esquema a medias."
if node scripts/apply-schema.mjs neon; then
  say "Esquema aplicado."
else
  SKIPPED+=("aplicar el esquema: node scripts/apply-schema.mjs neon")
  warn "la migración falló; revisa el mensaje de arriba antes de seguir"
fi
pause "Enter para seguir"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Verificar aislamiento y clonado"
say "Las dos garantías que sostienen el producto, contra el motor real: que un"
say "segundo usuario no llega a tus datos, y que clonar una Versión copia el"
say "árbol completo con la jerarquía remapeada."
note "Crea dos usuarios de prueba y hace rollback: no deja rastro."
if node scripts/verify-schema.mjs neon --applied; then
  say "Aislamiento y clonado verificados."
else
  SKIPPED+=("verificar el esquema: node scripts/verify-schema.mjs neon --applied")
  warn "seguimos, pero revisa esto antes de escribir código"
fi
pause "Enter para seguir"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Activar el interruptor"
say "Una variable decide qué Proveedor de Backend está activo. Cambiarla y"
say "redesplegar es todo lo que hace falta para volver a Supabase."
write_env NEXT_PUBLIC_BACKEND "neon"
say ""
note "En Vercel hay que ponerla también, o el despliegue seguirá apuntando al"
note "otro proveedor."
SKIPPED+=("NEXT_PUBLIC_BACKEND=neon en Vercel (los tres entornos)")

finish
